version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: "npm-modules"
          paths:
            - /node_modules
      - run: npm run lint
    test:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys:
              - "npm-modules"
        - run: npm install
        - run: npm run test
    analyze:
      docker:
        - image: circleci/node:13.8.0
        steps:
          - checkout
          - restore_cache:
              keys:
                - "npm-modules"
          - run: npm audit
workflows:
  default:
    jobs:
      build
      test:
        requires: [build]
      analyze:
        requires: [test]
